apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
   - name: http 
     port: 9371
     targetPort: 9371
   - name: metrics
     port: 8371
     targetPort: 8371
